I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 808, in script
    python:
  File "game/script.rpy", line 810, in <module>
    hero.turn_start(band)
  File "game/script.rpy", line 322, in turn_start
    self.player_turn(band)
  File "game/script.rpy", line 338, in player_turn
    self.action_select(band)
  File "game/script.rpy", line 342, in action_select
    self.choose_enemy(band, selected)
  File "game/script.rpy", line 347, in choose_enemy
    self.fight_weapon(chosen)
  File "game/script.rpy", line 185, in fight_weapon
    enemy.fire_skin_status_check()
TypeError: fire_skin_status_check() missing 1 required positional argument: 'enemy'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 808, in script
    python:
  File "/home/muaddyb/coding/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/muaddyb/coding/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 810, in <module>
    hero.turn_start(band)
  File "game/script.rpy", line 322, in turn_start
    self.player_turn(band)
  File "game/script.rpy", line 338, in player_turn
    self.action_select(band)
  File "game/script.rpy", line 342, in action_select
    self.choose_enemy(band, selected)
  File "game/script.rpy", line 347, in choose_enemy
    self.fight_weapon(chosen)
  File "game/script.rpy", line 185, in fight_weapon
    enemy.fire_skin_status_check()
TypeError: fire_skin_status_check() missing 1 required positional argument: 'enemy'

Linux-5.15.0-56-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
Strannik 1.0
Sat Jan 14 00:55:29 2023
